default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-mister-cocktail-solution_development

test:
  <<: *default
  database: rails-mister-cocktail-solution_test
